;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        autopair-insert-opening
        autopair-skip-close-maybe
        delete-horizontal-space
        indent-for-tab-command
        isearch-abort
        isearch-forward-regexp
        isearch-printing-char
        kill-region
        ns-copy-including-secondary
        org-beginning-of-line
        org-end-of-line
        org-kill-line
        org-metaleft
        org-metaright
        org-self-insert-command
        org-yank
        previous-buffer
        ))

(setq mc/cmds-to-run-once
      '(
        helm-M-x
        mark-whole-buffer
        markdown-exdent-or-delete
        next-buffer
        org-delete-char
        paredit-semicolon
        ))
