;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        autopair-insert-opening
        autopair-skip-close-maybe
        kill-region
        org-beginning-of-line
        org-metaleft
        org-metaright
        org-self-insert-command
        previous-buffer
        ))

(setq mc/cmds-to-run-once
      '(
        helm-M-x
        next-buffer
        org-delete-char
        paredit-semicolon
        ))
